name: Build OnePlus-Sm8150-Kernel-OOS11
on:
  workflow_dispatch:
  schedule:
      # Run once a week on Sunday at midnight. See http://crontab.guru
      - cron: '0 21 * * *'
  push:
    branches:
      - oneplus/OOS_SM8150_11.0
  pull_request:
    branches:
      - oneplus/OOS_SM8150_11.0

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "blu_spark_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-androidkernel- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1 O=out"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 1

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Remove unnecessary files
      run: |
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install -y lld clang-14 gcc-arm-linux-gnueabi gcc-aarch64-linux-gnu binutils make python3 libssl-dev build-essential bc bison flex unzip ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs
        git clone https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9 aarch64 --depth=1
        git clone https://github.com/khalidaboelmagd/AnyKernel3
        rm -rf AnyKernel3/.git

    - name: Get Version
      id: get_version
      run: |
        cd KernelSU
        git fetch --unshallow
        git pull
        git rev-list --count HEAD
        echo "VERSION=$(expr $(git rev-list --count HEAD) + 10200)" >> $GITHUB_OUTPUT
        cd ..

    - name: Build KernelSU
      run: |
       export PATH=$(pwd)/clang/bin/:$(pwd)/aarch64/bin/:$PATH
       export ARCH=arm64
       export SUBARCH=arm64
       export LD=ld.lld
       export BRAND_SHOW_FLAG=oneplus
       export TARGET_PRODUCT=msmnile
       export EXTRA_CFLAGS="-Wno-deprecated-declarations"
       curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next-susfs/kernel/setup.sh" | bash -s next-susfs
       make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC="ccache clang-14" EXTRA_CFLAGS="$EXTRA_CFLAGS"
       make $KERNEL_CMDLINE -j$(nproc --all) CC="ccache clang-14" EXTRA_CFLAGS="$EXTRA_CFLAGS"
       cp out/arch/arm64/boot/Image AnyKernel3

    - name: Create AK3 zip for android 11
      run: |
       cd AnyKernel3
       zip -r ../OP7-OOS11-KernelSU-${{ steps.get_version.outputs.VERSION }}.zip *
       cd ..

    - name: Upload to Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          OP7-OOS11-KernelSU-${{ steps.get_version.outputs.VERSION }}.zip
        name: OnePlus7_KernelSU-${{ steps.get_version.outputs.VERSION }}
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        body: |
          Device: Oneplus 7/Oneplus 7Pro/Oneplus 7T/Oneplus 7TPro
          Target:OOS11
